# Characters shown in front of the query.
prompt = ''

# space between window border and the content in pixel
padding = 100

fonts = [
    'JuliaMono',
    'Noto Sans Mono',
    'Monospace',
] # list of otf or ttf fonts. later elements work as fallback
font_size = 32.0

[history]
decrease_interval = 48 # interval to decrease the number of launches in hours

[colors]
# color format: rgb or rgba, if transparency is desired
background = '#323232dd'
prompt = '#abb2bfff'
text = '#888888ff'          # for search results
text_query = '#e5c07bff'    # for the search query
text_selected = '#4c7899ff' # for the currently selected result

[keybindings]
# keybindings syntax: ctrl/shift/alt/logo as modifiers and a key joined by '+' signs
# A list of available keys can be found here: https://docs.rs/crate/x11-keysymdef/0.2.0/source/src/keysym.json
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return", "ctrl+j"]
delete = ["KP_Delete", "Delete", "BackSpace", "ctrl+d"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace", "alt+d"]
complete = ["Tab"]
nav_up = ["ctrl+p"]
nav_down = ["ctrl+n"]
exit = ["Escape", "ctrl+g"]
