#!/usr/bin/env python

import os
import atexit
from pathlib import Path

from readline import read_history_file

state_dir = Path(os.environ['XDG_STATE_HOME']) / 'python'

if not state_dir.is_dir():
    state_dir.mkdir()

history_file = str(state_dir / 'history')

try:
    read_history_file(history_file)
except OSError:
    pass

def write_history():
    from os import environ
    from readline import write_history_file
    from pathlib import Path

    state_dir = Path(environ['XDG_STATE_HOME']) / 'python'

    if not state_dir.is_dir():
        state_dir.mkdir()

    history_file = str(state_dir / 'history')

    try:
        write_history_file(history_file)
    except OSError:
        pass

atexit.register(write_history)
