[settings]
activate_aggressive = false
all_compile = false
always_keep_download = false
always_keep_install = false
auto_install = true
cache_prune_age = "7d"
color = true
default_config_filename = "mise.toml"
default_tool_versions_filename = ".tool-versions"
http_timeout = "10s"
idiomatic_version_file_enable_tools = [
    "go",
]

[settings.python]
default_packages_file = "~/.config/python/default-requirements.txt"

[settings.ruby]
default_packages_file = "~/.config/ruby/default-gems"

[settings.rust]
cargo_home = "~/.local/share/cargo"
rustup_home = "~/.local/share/rustup"

[[tools."aqua:atuinsh/atuin"]]
    version = "latest"

[[tools.go]]
    version = "latest"

[[tools."pipx:python-poetry/poetry"]]
    version = "latest"

[[tools.python]]
    version = "latest"

[[tools.ruby]]
    version = "latest"

[[tools.rust]]
    version = "latest"
    components = "cargo,clippy,rust-analysis,rust-analyzer,rust-docs,rust-src,rust-std,rustc,rustfmt"

[[tools."aqua:starship/starship"]]
    version = "latest"

[[tools."asdf:mise-plugins/mise-tmux"]]
    version = "latest"

[[tools."cargo:usage-cli"]]
    version =  "latest"
